library(lubridate)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, sep=";", na.strings = "?", stringsAsFactors = FALSE)
data$Date <- dmy(data$Date)
data <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02")
png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
day_labels <- c("Thu", "Fri", "Sat")
location <- c(0, 1450, 2900)
plot(data$Global_active_power, type="l", ylab = "Global Active Power", xaxt = "n", xlab = "")
axis(side = 1, at = location, labels = day_labels)
plot(data$Voltage, type = "l", ylab = "Voltage", xaxt = "n", xlab = "datetime")
axis(side = 1, at = location, labels = day_labels)
plot(data$Sub_metering_1, type="l", xaxt = "n", ylab = "Energy sub metering", xlab = "")
lines(data$Sub_metering_2, col="red")
lines(data$Sub_metering_3, col="blue")
axis(side = 1, at = location, labels = day_labels)
legend("topright", col=c("black", "red", "blue"), lty = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
plot(data$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xaxt = "n", xlab = "datetime")
axis(side = 1, at = location, labels = day_labels)
dev.off()