library(lubridate)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, sep=";", na.strings = "?", stringsAsFactors = FALSE)
data$Date <- dmy(data$Date)
data <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02")
par(bg = "white")
hist(data$Global_active_power, col="red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power", bg = "white")
dev.copy(png, file = "plot1.png", width = 480, height = 480)
dev.off()