library(lubridate)
data <- read.table("./data/household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?", stringsAsFactors = FALSE)
data$Date <- dmy(data$Date)
data <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02")
par(bg = "white")
plot(data$Global_active_power, type="l", ylab = "Global Active Power (kilowatts)", xaxt = "n", xlab = "")
day_labels <- c("Thu", "Fri", "Sat")
location <- c(0, 1450, 2900)
axis(side = 1, at = location, labels = day_labels)
dev.copy(png, file="plot2.png", width = 480, height = 480)
dev.off()