library(lubridate)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
data <- read.table(unz(temp, "household_power_consumption.txt"), header = TRUE, sep=";", na.strings = "?", stringsAsFactors = FALSE)
data$Date <- dmy(data$Date)
data <- subset(data, data$Date >= "2007-02-01" & data$Date <= "2007-02-02")
par(bg = "white")
png(filename = "plot3.png", width = 480, height = 480, units = "px")
plot(data$Sub_metering_1, type="l", xaxt = "n", ylab = "Energy sub metering", xlab = "")
lines(data$Sub_metering_2, col="red")
lines(data$Sub_metering_3, col="blue")
day_labels <- c("Thu", "Fri", "Sat")
location <- c(0, 1450, 2900)
axis(side = 1, at = location, labels = day_labels)
legend("topright", col=c("black", "red", "blue"), lty = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()